QA-235: pipeline: Switch to static checks by golangci-lint
mendersoftware/azure-iot-manager pull request #8
Opened 2021-11-16 20:23 UTC by lluiscampos

Modify the existing .golangci.yml to follow standard and fix few linting
issues. Removed migration_1_0_0.go as it was completely unused.

2021-11-16 20:25 UTC, lluiscampos commented
@mender-test-bot start pipeline :one::two:

2021-11-17 04:16 UTC, tranchitella requested changes
We cannot remove migration 1.0.0, if we are not using it, it's a bug and we have to fix it.

2021-11-17 08:33 UTC, lluiscampos commented
> We cannot remove migration 1.0.0, if we are not using it, it's a bug and we have to fix it.

I suspected that.

It has been "fixed" in #4, so I'll rebase and rework :smiley:

2021-11-17 08:44 UTC, lluiscampos commented
@tranchitella Fixed now. All linting issues were fixed by @alfrunes in #4, so this PR now is basically replacing the template :+1:

2021-11-17 08:50 UTC, alfrunes approved these changes

2021-11-17 08:50 UTC, alfrunes commented on .golangci.yml
> +    tab-width: 4
:see_no_evil:

2021-11-17 09:38 UTC, tranchitella approved these changes

2021-11-17 10:28 UTC, merged